### ISSUE TITLE
Thanks for sharing, and maybe some inspiration for extensions ;-)

### ISSUE THREAD

**Issue by gerardwr** [jeffmer/P8Apps#1]
Hi,

Just want to say thanks sharing your Espruino version with emulation of the Bangle functionality on the P8.

Installed it yesterday, your Espruino works fine on the P8, including the functions for the lcd. Also tried your Apploader, also works fine.

Excellent work!

Last year I created my own Bangle-compliant P8 module, using the unbuf Espruino version as shared by @atc1441. But in the meantime I have switched to other things.

Maybe my list of supported Bangle compliant functionality inspires you for extensions ;-). I tried to mimic as much Bangle functions as possible, because it avoids the need to write proper documentation.

Note that my getHeartRate and getStepcount functions do not deliver the right data, still struggling with correct code for interpreting HW-registers. Will have a look at your code for inspiration ;-)

```
>P8
={
  buzz: function (time,strength) { ... },
  g: Graphics: {
    flip: function () { [native code] },
    on: function () { ... },
    off: function () { ... }
   },
  getAccel: function () { ... },
  getBattery: function (s) { ... },
  getHeartRate: function () { ... },
  getStepCount: function () { ... },
  isCharging: function () { ... },
  isLCDOn: function () { ... },
  LCDOff: function () { ... },
  LCDOn: function () { ... },
  setHRMPower: function (isOn) { ... },
  setLCDBrightness: function (bri) { ... },
  setLCDPower: function (isOn) { ... },
  setLCDTimeout: function (secs) { ... },
  setPollInterval: function (int) { ... },
  "#onlcdPower": function (isOn) { ... },
  "#onbutton": function (pin) { ... },
  "#oncharging": function (isCharging) { ... },
  "#onswipe": function (direction) { ... },
  "#ontouch": function (x,y,long) { ... },
  "#onaccel": function (xyz) { ... },
  "#onfaceup": function (up) { ... },
  "#ontwist": function () { ... },
  brightness: 7, LCDTimeout: 5000, pollInterval: 2, faceUp: true, twist: false }
```

The source of my P8 modules is added below, for anyone that is interested. Just for reference, no guarantees.
[BangleCompliantModuleForP8.js.txt](https://github.com/jeffmer/P8Apps/files/5888212/BangleCompliantModuleForP8.js.txt)

**Comment by jeffmer** [comment]
Thanks for your input - really appreciated
