### ISSUE TITLE
About the firmware  version and update

### ISSUE THREAD

**Issue by tyrone1984** [jeffmer/P8Apps#2]
Thanks!
i have built the The firmware  based the repository https://github.com/jeffmer/Espruino,  but the Version number is `espruino_2v08.447_p8 ` not the  `espruino_2v08.63_p8`??
Can you tell me how to update?

**Comment by jeffmer** [comment]
That’s fine, version numbers are local not global. I recently updated the repository to sync it with the official Espruino repository and if you look, the p8 firmware is now espruino_2v08.301_p8_SDK12_SD30_SPIFLASH.zip.

**Comment by tyrone1984** [comment]
Great! 
I'm going to try...
