### ISSUE TITLE
Supported color range

### ISSUE THREAD

**Issue by abhigkar** [jeffmer/P8Apps#9]
Hi Thanks for amazing lcd_spi_unbuf library. I am using this library (C code) for ID107 HR plus Color which has 80x160 ST7735 oled
How many colors are supported for this lib? I have set the SPISENDMANY_BUFFER_SIZE=80 in board file

**Comment by jeffmer** [comment]
Full 16 bit colour is supported. I.e Red 5 bits Green 6 bits Blue 5bits.
